Add ZeDMD WiFi support
vpinball/libdmdutil pull request #49
Opened 2024-09-06 21:50 UTC by bartdesign

Added ZeDMD Wifi support, updated dmdserver.ini and README.md with the new wifi options.

2024-09-06 21:54 UTC, jsm174 commented on README.md
> +WifiIP =
WiFiEnabled
WiFiAddr
WiFiPort

To stay with style and names already in libzedmd

2024-09-06 21:54 UTC, jsm174 commented on include/DMDUtil/Config.h
> +  bool IsZeDMDWifiEnabled() const { return m_zedmdWifiEnabled; }
WiFiEnabled - see comment above

2024-09-06 21:54 UTC, jsm174 commented on src/DMD.cpp
> +            if (pConfig->IsZeDMDWifiEnabled())
WiFi

2024-09-06 21:54 UTC, jsm174 commented on src/DMD.cpp
> +              std::string wifiAddr = pConfig->GetZeDMDWifiAddr() ? pConfig->GetZeDMDWifiAddr() : "";
WiFiAddr

2024-09-06 21:54 UTC, jsm174 commented on src/dmdServer.cpp
> +      pConfig->SetZeDMDWifiAddr(r.Get<string>("ZeDMD", "WifiIP", "").c_str());
WiFI

Addr instead of IP

2024-09-07 08:41 UTC, mkalkbrenner requested changes
The libzedmd version needs to be raised to a7c9ba92d1ca3418ff3d93b2f99a62f60e99d672 in the externals scripts.

2024-09-07 08:41 UTC, mkalkbrenner commented on dmdserver.ini
> +# Set to 1 if ZeDMD or ZeDMD WiFI is attached.
In DMDext we treat ZeDMD and ZeDMD WiFi as different devices. For example, ZeDMDWiFi doesn't support setting brightness or RGB order over the WiFi stream.

And it would be nice to have the possibility to attach two devices, one via USB within the cab and a second via WiFi at the wall ;-)

But maybe we can do the split in a second step.

2024-09-07 08:41 UTC, mkalkbrenner commented on dmdserver.ini
> +WiFiPort =
In DMDext you could configure the SSID and the password. If set, ZeDMD gets connected in USB, not WiFi mode, and the these credentials will be set on the device, just like we do it for brightness and RGB order:
https://github.com/freezy/dmd-extensions/blob/c461fd4a4420c16e0628cc575075c371a62dc177/PinMameDevice/DmdDevice.ini#L293

Then you have to remove the credentials from the settings again and libdmdutil will connect via WiFi at the next start.

This way you don't need an external tool or the command line to set the WiFi credentials.

I think we should offer the same. But maybe in a second PR.

2024-09-07 08:41 UTC, mkalkbrenner commented on src/DMD.cpp
> +                // Fix RGB and brightness
wrong comment

2024-09-07 10:40 UTC, jsm174 commented
Make sure we do a squash merge on this when ready as well!

2024-09-07 14:04 UTC, bartdesign commented
> The libzedmd version needs to be raised to a7c9ba92d1ca3418ff3d93b2f99a62f60e99d672 in the externals scripts.

Fixed

2024-09-07 14:05 UTC, bartdesign commented on src/DMD.cpp
> +                // Fix RGB and brightness
fixed

2024-09-07 14:06 UTC, bartdesign commented on dmdserver.ini
> +WiFiPort =
A PR is incoming for ZeDMD to Wifi configuration directly on the device. We can always add wifi conf via serial later if this will be preferred.

2024-09-07 14:14 UTC, bartdesign commented on dmdserver.ini
> +# Set to 1 if ZeDMD or ZeDMD WiFI is attached.
I believe we only need to modify findDisplays to get simultaneous functionality working. My question is: how should we handle failures? If I have both a ZeDMD Serial and a ZeDMD Wifi configured in the dmdserver.ini, should the thread stop if it fails to find one of them, or should it continue with whichever one is available?

2024-09-07 14:56 UTC, bartdesign commented on dmdserver.ini
> +# Set to 1 if ZeDMD or ZeDMD WiFI is attached.
> In DMDext we treat ZeDMD and ZeDMD WiFi as different devices. For example, ZeDMDWiFi doesn't support setting brightness or RGB order over the WiFi stream.
> 
> And it would be nice to have the possibility to attach two devices, one via USB within the cab and a second via WiFi at the wall ;-)
> 
> But maybe we can do the split in a second step.

See the latest commit; i have changed it to working with 2 at the same time and seperated the config stuff.

2024-09-07 14:58 UTC, bartdesign commented
I have updated the code so the ZeDMD-WiFi has it's own config and can work at the same time with Serial.

2024-09-07 15:00 UTC, bartdesign commented on dmdserver.ini
> +# Set to 1 if ZeDMD or ZeDMD WiFI is attached.
For now i have setup the error handeling that it will continue of it finds one of the 2 configured displays. Let me know what is the best way to handle this.

2024-09-08 08:27 UTC, mkalkbrenner requested changes
@bartdesign @jsm174
I think we should merge this as soon as the the network address is changed to 127.0.0.1.
The PR introduces a new ZeDMD-WiFi section in the config file, which is good and the base to support both variations in parallel.
Then @bartdesign has a working version and we can continue to split the ZeDMD threads in a new PR.

2024-09-08 08:27 UTC, mkalkbrenner commented on dmdserver.ini
> +[ZeDMD-WiFi]
I don't want to put all the load on @bartdesign.
But we should discuss things here.
I think having a separate device here is the right choice as you also have to decide which firmware to flash on ZeDMD, WiFi or USB. (WiFi has minimal USB support to support the settings features.)

But the code later on here doesn't support two devices at the same time.
We need to treat ZeDMD and ZeDMD WiFi like ZeDMD and Pixelcade as two different things.
That means that we have two threads if both are enabled, a ZeDMD thread and a ZeDMD WiFi thread. For sure we can re-use the entire threading code.

2024-09-08 08:27 UTC, mkalkbrenner commented on src/DMD.cpp
> +          if (openSerial || openWiFi)
openSerial should start m_pZeDMDThread,
openWiFi should start m_pZeDMDWiFiThread.

We also need two pointers, pZeDMD and pZeDMDWiFi

2024-09-08 08:27 UTC, mkalkbrenner commented on dmdserver.ini
> +Addr = 0.0.0.0
I agree with @jsm174 that 127.0.0.1 is the better and safer default.
I understand that the usage should be as easy as possible.
But you don't sell a car without a handbrake just because people might to forget to release it before driving.
The default usage for dmdserver is to run on the same machine as the clients like VPX or batocera. In your new handheld device, dmdserver will also run on the same device or you would use libdmdutil directly (embedded in VPX).

2024-09-08 14:42 UTC, merged